micronaut:
  application:
    name: micrometer
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
netty:
  default:
    allocator:
      max-order: 3
